### ISSUE TITLE
Future: Laravel 5.5 LTS

### ISSUE THREAD

**Issue by fishmad** [roladn/laravel-sentinel-crud-starter#1]
Any plans to bring this up to 5.5 LTS?

Great app btw.

**Comment by rolandalla** [comment]
Yeap , I will updated it to 5.5 soon :)
Thank you for using this Starter.
Regards

**Comment by fishmad** [comment]
Hi Roladn

Is is possible to publish the stubs that generate the blade views or override them somehow in the resources folder so I can make changes to them outside the vendor folder?
C:\laragon\www\laravel-sentinel-crud-starter-master\vendor\roland\crud\src\Commands\stubs

I used a similar one a couple of years ago but the developer is not longer supporting it.
https://github.com/pingpong-labs/generators/tree/2.1

the user can optionally publish the stubs to resources folder, make changes as required and when they generate any new crud or views it would use the stubs found in /resources/assets/vendor/roland/stubs/
if the crud generator does not find custom published stubs in that resources folder than id just defaults back to the vendors built-in ones.

**Comment by rolandalla** [comment]
Hi Dear,
To override the default template with yours, turn on custom_template option in the config/crudgenerator.php file.

`'custom_template' => true,`

Also change  your path for the new sub. 
`'path' => base_path('resources/your_sub_folder'),`
Copy and paste all sub folder from package into your new_sub_folder and change them as you need .
Hope this help.
