### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Farris27** [roladn/laravel-sentinel-crud-starter#2]
How add permission to a custom controller? 

my rout: 

  Route::post('produitGammes/edit','ProduitGammesController@edition');
  Route::resource('produitGammes','ProduitGammesController');
  Route::post('produitGammes/save','ProduitGammesController@save');

my controller: 

public function edition(){

    }

    public function save(){

    }

But i don't look this permissions in my gestion of controller ... 

Thanks for your package 👍

**Comment by rolandalla** [comment]
Hello ,
The costom routes mast be like this:

`Route::get('produitGammes/edit', ['uses' => 'ProduitGammesController@edition', 'as' => 'product.edit']);`

Try this comands to refresh the routes.
`php artisan route:cache`
` php artisan api:cache`

Regards

**Comment by Farris27** [comment]
Hi 


it works !

Thanks very much :)

**Comment by rolandalla** [comment]
You are welcome.
Thank you for using my package.
Regards
